services:
  server:
    container_name: chi-boilerplate-server
    # image: chi-boilerplate-server:latest
    build: .
    ports: 
      - 3002:3002
    restart: on-failure
    networks:
      - backend

networks:
  backend:
    driver: bridge
